services:
  - type: web
    name: academix-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r "python backend/requirements.txt"
    startCommand: gunicorn --chdir "python backend" app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: OLLAMA_API_KEY
        sync: false
      - key: OLLAMA_HOST
        value: https://ollama.com # Or your specialized host
      - key: PYTHON_VERSION
        value: 3.10.0
